# Generated by Django 3.2.8 on 2021-11-03 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('place', models.CharField(default='', max_length=255, verbose_name='Место')),
                ('status', models.CharField(choices=[('init', 'Готово к отправке'), ('sent', 'Отправлено'), ('cancelled', 'Отменено'), ('error', 'Ошибка')], default='init', max_length=9, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('publish_at', models.DateTimeField(verbose_name='Дата и время напоминания')),
                ('task_id', models.CharField(default='', max_length=255, verbose_name='ID задачи в Celery')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('users', models.ManyToManyField(blank=True, related_name='_reminders_reminder_users_+', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Напоминание',
                'verbose_name_plural': 'Напоминания',
            },
        ),
    ]
